[DRAFT] default log folder on initialize
Project-OSmOSE/OSEkit pull request #205
Opened 2024-10-04 11:07 UTC by Gautzilla

Right know, trying to create new spectrograms from a dataset that doesn't need reshaping (with bypassing the `initialize()` step) raises an exception because the folder creation is skipped.

This PR is linked to changes in the [datarmor toolkit](https://github.com/Project-OSmOSE/datarmor-toolkit/blob/main/src/utils_datarmor.py): right know, `build_job_files`'s `logdir` folder is optional, but should be mandatory.

Fixing that implies:

- making the `logdir` directory mandatory
- create the folder in which the spectrograms are to be stored even if the audio doesn't need to be reshaped

Changes also have to be done in the [datarmor toolkit](https://github.com/Project-OSmOSE/datarmor-toolkit/blob/main/src/utils_datarmor.py) to account for the case where a user wants to create spectrograms without reshaping the audio.

2024-10-04 11:08 UTC, Gautzilla commented
[The first commit](https://github.com/Project-OSmOSE/OSEkit/pull/205/commits/d8300520a9898e441df0631d1d0ae3d48a9a75fd) only takes the first step into consideration.

2024-10-08 14:44 UTC, Gautzilla commented
This is still a bit patchy since everything here might be changed with the rewriting of OSEkit, but basically:

- A problem arose when trying to use `generate_spectro` from an already-initialized spectrogram (that is when you want to output new spectrograms without needing to reshape the audio files): I added the `prepare_paths` methods that just reflects `__build_path` to be called from outside the class (typically by the qsub generator in datarmortoolkit)
- In the `datarmortoolkit` (see the [linked PR](https://github.com/Project-OSmOSE/datarmor-toolkit/pull/57)), I needed to pass the infos about the `Spectrogram` configuration from `generate_spectro` to `qsub_spectrogram_generator_pkg`. Since I couldn't directly pass the class instance, I:
    - Added a `from_csv` class method to initialize a `Spectrogram` object from the `metadata.csv` created in the spectrogram output folder
    - wrote the spectrogram metadata in `generate_spectro` before creating the job files (a call to `prepare_paths` was necessary for the Spectrogram object to correctly parse the folder in which it writes the csv)
    - Retrieved the `Spectrogram` object from this created metadata csv

Moreover, it seems the job file creation was broken in case where the jobs were created in `generate_spectro`: `dataset.jb.submit_job` was called without a link to the newly created jobfiles (unless I'm missing something here):
```py
job_id_list = dataset.jb.submit_job(
        dependency=pending_jobs
    )  # submit all built job files
```

I stored the job files that were created within `build_spectro` in a list and called `dataset.jb.submit_job` for each file in this list.

Overall, it seems to work just fine for the tests I did on small datasets. 

I'm currently generating ~13k spectrograms using 10 parallel jobs with the current script to test it on a larger scale (I'll need @MaelleTtrt 's look on the created spectrograms and welchs to confirm that it ran flawlessly!)

2024-10-09 13:16 UTC, mathieudpnt requested changes
This worked fine for me ! I will approve once the codes are black formatted !

2024-10-11 07:08 UTC, mathieudpnt approved these changes

2024-10-11 07:09 UTC, merged