[DRAFT] rename build files test
Project-OSmOSE/OSEkit pull request #210
Opened 2024-10-15 09:27 UTC by Gautzilla

This PR follows the changes made regarding issue #209

2024-10-17 15:06 UTC, Gautzilla commented
@mathieudpnt @cazaudo, basically this PR does:

A rework of how the timestamps are parsed from the audio file names. I added some basic utils which might simplify the old `write_timestamp` function:
- Dataset now uses the `_write_timestamp_csv_from_audio_files` function to write the timestamp csv from the audio files present in the audio folder. this function:
  -  get the supported audio files from the audio files folder
  - parse the Timestamps from the audio file names thanks to the provided format pattern string (this is the step that uses all the added utils, see `associate_timestamps` in the `utils\timestamp_utils` module)
  - write the timestamps.csv with the uniformed OSmOSE datetime string format (defined in the `config` module)

I added a bunch of unit and integration tests to make the thing robust, and it should not break the global (untested) OSEkit workflow since the timestamp.csv is written in the same fashion as before (except for the timestamp precision, which has been reduced to the millisecond).

I intentionally kept the `build()` method as it is for now (and integrated the latter changes to it), but these changes might help refactoring the `build()` method (I think this is the next step!)

PS: pytest throws some warnings on the Python 3.10 used in the github actions here. I managed to solve them locally in an environment that uses Python 3.12.7: is there a reason for sticking with the 3.10 version?

2024-10-22 08:16 UTC, mathieudpnt requested changes
a few minor changes, overall looks good to me!

2024-10-22 08:16 UTC, mathieudpnt commented on src/OSmOSE/utils/timestamp_utils.py
> +    arameters
typo here

2024-10-22 08:16 UTC, mathieudpnt commented on src/OSmOSE/utils/timestamp_utils.py
Could you modify also `substract_timestamp` function so it does not use any function from datetime but pandas instead ?
I think we should stick to pandas functions only now thoughout the codes

2024-10-22 08:16 UTC, mathieudpnt commented on src/OSmOSE/Dataset.py
Same comment than in `timestamp_utils.py`

2024-10-22 08:51 UTC, Gautzilla commented on src/OSmOSE/Dataset.py
Indeed, I didn't modify the existing stuff yet.

I can do it within this PR, but it'll take a bit more time (since there's no existing test, it requires some precaution not to break anything) and I'll had to add some tests I guess!

2024-10-22 08:52 UTC, Gautzilla commented on src/OSmOSE/utils/timestamp_utils.py
Yup, I didn't modify the existing timestamp utils, which I know have to be changed. As I answered to the other comment, I think it indeed fits in this PR, but it'll require some time to write the good tests and check that nothing's broken!

2024-10-22 08:53 UTC, mathieudpnt commented on src/OSmOSE/Dataset.py
If you plan on doing it later that's fine by me ! 🥸

2024-10-22 09:39 UTC, mathieudpnt approved these changes

2024-10-22 09:39 UTC, Gautzilla commented on src/OSmOSE/utils/timestamp_utils.py
> +    arameters
Fixed in [d1ee2d8](https://github.com/Project-OSmOSE/OSEkit/pull/210/commits/d1ee2d88cc90271e5a6c381ae2cfeca6cfbfd15e)

2024-10-22 09:42 UTC, Gautzilla commented on src/OSmOSE/utils/timestamp_utils.py
I'll integrate these changes in a new branch right after this one is merged!

2024-10-22 09:48 UTC, merged